### ISSUE TITLE
Changed tts engine to parler in script.py webui. No longer launches: ModuleNotFoundError: No module named 'parler_tts'

### ISSUE THREAD

**Issue by Urammar** [erew123/alltalk_tts#376] opened 2024-10-13 17:39 UTC
🔴 If you have installed AllTalk in a custom Python environment, I will only be able to provide limited assistance/support. AllTalk draws on a variety of scripts and libraries that are not written or managed by myself, and they may fail, error or give strange results in custom built python environments.

🔴 Please generate a diagnostics report and upload the "diagnostics.log" as this helps me understand your configuration.

https://github.com/erew123/alltalk_tts/tree/main?#-how-to-make-a-diagnostics-report-file

**Describe the bug**
Traceback (most recent call last):   File "/home/bengaman/MyShitLinix/AI/text-generation-webui-main/extensions/alltalk_tts/tts_server.py", line 171, in <module>     loader_module = importlib.import_module(f"system.tts_engines.{engine_loaded}.model_engine")                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "/home/bengaman/MyShitLinix/AI/text-generation-webui-main/installer_files/env/lib/python3.11/importlib/__init__.py", line 126, in import_module     return _bootstrap._gcd_import(name[level:], package, level)            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^   File "<frozen importlib._bootstrap>", line 1204, in _gcd_import   File "<frozen importlib._bootstrap>", line 1176, in _find_and_load   File "<frozen importlib._bootstrap>", line 1147, in _find_and_load_unlocked   File "<frozen importlib._bootstrap>", line 690, in _load_unlocked   File "<frozen importlib._bootstrap_external>", line 940, in exec_module   File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed   File "/home/bengaman/MyShitLinix/AI/text-generation-webui-main/extensions/alltalk_tts/system/tts_engines/parler/model_engine.py", line 35, in <module>     from parler_tts import ParlerTTSForConditionalGeneration ModuleNotFoundError: No module named 'parler_tts'

**To Reproduce**
Steps to reproduce the behaviour:

Changed tts engine to parler in script.py webui. No longer launches.

**Screenshots**

**Text/logs**
If applicable, copy/paste in your logs here from the console.

**Desktop (please complete the following information):**
AllTalk was updated: [approx. date]
Custom Python environment: [yes/no give details if yes]
Text-generation-webUI was updated: [approx. date]

**Additional context**

**Comment by phazei** [comment] 2024-10-13 19:44
Same issue here.  
https://github.com/erew123/alltalk_tts/issues/374

**Comment by erew123** [comment] 2024-10-13 23:14
Hi @Urammar 

Please read [this here](https://github.com/erew123/alltalk_tts/issues/377). Apologies for your install problems, but I hope that may give you a way forward. If it does and you are happy with that resolution, please close the ticket for now. If not, feel free to leave it open and I will return to it when I can.

Thanks

**Comment by Urammar** [comment] 2024-10-14 08:33
> Same issue here. #374

I posted the temp fix there, you can recover easily enough and get back into bootable state. Doesn't fix the fundamental bug but at least you can launch the app again.

**Comment by Pudzianos** [comment] 2024-10-15 23:38
@Urammar thank you, this helped me :)

**Comment by erew123** [comment] 2024-10-20 05:50
Hi 

Im finally in a place where I can test through things. Ive run a full installation from scratch and cant find an issue with install, so I suspect this must have been caused by a Github blip at some point. Sometimes for a variety of reasons (internet related or Github related) bits just dont download during install. Ive seen it a few times with the DeepSpeed portion of the download/install, and the fact that two of you had an issue, makes me think it was Github related, rather than a routing issue on the internet. 

As I cant currently find an issue, Im going to close this off for now. Though I intend at some point to make an extra routing for a "reinstall X part of AllTalk/TTS engine" to make things a bit more robust where needed.

Thanks

**Closed by erew123** 2024-10-20 05:50 UTC
