### ISSUE TITLE
Dockerfile not working

### ISSUE THREAD

**Issue by JanEisen** [erew123/alltalk_tts#200] opened 2024-05-03 16:51 UTC
**Describe the bug**
When building the container using the Dockerfile in main branch i get the error that the 
`sh: 1: ./launch.sh: not found`

**To Reproduce**
- docker build . -t alltalk_tts 
- docker run localhost/alltalk_tts:latest

anyone knows how to fix this?

**Comment by erew123** [comment] 2024-05-05 10:25
Hi @JanEisen 

Docker as mentioned on the front of Github is not exactly something Im covering at the moment (statement on it here) https://github.com/erew123/alltalk_tts?tab=readme-ov-file#-docker-builds-and-google-colabs

Someone else built it and I've had quirks with the docker build, such as the launch sometimes working and sometimes not. After I spent ??? hours attempting to find a permanent solution for docker & google colab, I figured I'm wasting my time and it would be better spent coding and resolving the issues that way. As such, that's what I'm doing and I'm attempting to get v2 of AllTalk completed.

As part of v2, I will get a google colab and docker build working. v2 is 50-60% built at the moment and I hope to have something out in the next week or two as a beta for people to work with (hopefully).

**As for your specific issue you mention** as mentioned I have hit that issue when I tried to resolve it. It baffles me, as if you load a terminal/shell and manually bash launch.sh, it all starts up. I've even thrown the startup/settings at 2x AI's and they have said all should be fine! Maybe someone else will have a solution.

I can leave this ticket open for a while if you wish? All I can say for sure is that v2 should be simpler to boot/start up, which in my tests, should make docker and google colab start easier.

Thanks

**Comment by Fantastic0482** [comment] 2024-05-05 20:27
The issue is the line endings. It needs to be normalized to LF, not CRLF. Use a text editor or add a .gitattributes file.

**Comment by erew123** [comment] 2024-05-06 00:40
@Fantastic0482 Thanks! I hadnt picked up on that. Ive run them through dos2unix and uploaded the changes.

@JanEisen assumedly this should resolve it now if you git pull the changes.

Thanks

**Closed by erew123** 2024-05-06 00:40 UTC

**Comment by JanEisen** [comment] 2024-05-06 10:10
Thanks a lot you both!
